name: MovieAppBuild
on:
  pull_request :
    branches : [ master ]
  push :
    branches: [ master ]


jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Java JDK
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: gradle

      - name: Set up Android SDK
        uses: android-actions/setup-android@v2
        with:
          api-level: 35
          build-tools: '35.0.0'
          ndk: '24.0.8215888'

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@af1da67850ed9a4cedd57bfd976089dd991e2582

      - name: Set permission Gradle
        run: chmod +x ./gradlew

      - name: Create local.properties
        run: echo "sdk.dir=$ANDROID_SDK_ROOT" > local.properties

      - name: Build with Gradle
        run: ./gradlew assembleDebug

      - name: Build Scan
        run: ./gradlew build --scan

      - name: Upload Build Artifact
        uses: actions/upload-artifact@v4.4.0
        with:
          name: Debug Artifact Apk
          path: app/build/outputs/apk/debug/movie-app-debug.apk

