name: MovieAppBuild
on:
  pull_request :
    branches : [ master ]
  push :
    branches: [ master ]


jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Java JDK
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'adopt'

      - name: Set permission Gradle
        run: chmod +x ./gradlew

      - name: Run unit tests
        run: ./gradlew clean testDebug

